[tool.black]
line-length = 88
target-version = ['py37', 'py38']

[tool.coverage.run]
omit = ["*/tests/*", "members/migrations"]

[tool.poetry]
name = "forenings_medlemmer"
version = "1.2"
description = "Forenings system for Coding Pirates"
authors = ["Benjamin Rotendahl <Benjamin@Rotendahl.dk>"]

[tool.poetry.dependencies]
python = "^3.8.0"
black = "20.8b1"
codecov = "2.1.9"
dj-database-url = "0.5.0"
dj-email-url = "1.0.1"
django = "3.1.1"
django-bootstrap4 = "2.2.0"
django-cors-headers = "3.5.0"
django-crispy-forms = "1.9.2"
django-cron = "0.5.1"
django-extensions = "3.0.5"
environs = "8.0.0"
factory-boy = "3.0.1"
flake8 = "3.8.4"
freezegun = "1.0.0"
graphene_django = "2.13.0"
gunicorn = "20.0.4"
psycopg2 = "2.8.6"
quickpay-api-client = "2.0.1"
sentry-sdk = "0.19.4"
tqdm = "4.59.0"
whitenoise = "5.2.0"
pydotplus = "2.0.2"
selenium = "3.141.0"
